### PR TITLE
Features/food menu widget

### PR DESCRIPTION
**Pull request by a-kkwan**
## Description

The Food Menu Widget containing contains a Week component (not a separate vue file/component, it is built into the widget), and the week component will contain a Day component (separate PR). This is to show Sherbrooke residents the meal choices on the week and day. 
 
## Related Issue or Trello Card

[Trello card](https://trello.com/c/IXCXFWZ2/3-food-menu-front-end)

## Motivation and Context

To ensure that a food menu fits with the Material theme the application is adopting, and also to implement a food menu widget that displays food menus for the week/day, has ability to delete weeks, ability to add weeks, save changes and schedule the menu. The user also cannot delete the first week and cannot add more than five weeks. 

## How Has This Been Tested?

- [x] Unit test
- [ ] NightWatch test
- [ ] Coverage testing
- [x] Manual testing

## Test Cases and test paths

The test cases are unfinished and some are also marked with TO DO. This is because the component will change in the future when integrating it with the Day components, so likely the tests will need to be heavily modified. Some unit tests regarding testing the default data contents are also present. 

## Screenshots (if appropriate):
screen shot 2018-03-23 at 10 27 57 pm
screen shot 2018-03-23 at 10 28 08 pm
screen shot 2018-03-23 at 10 28 28 pm
screen shot 2018-03-23 at 10 28 33 pm
screen shot 2018-03-23 at 10 28 57 pm
screen shot 2018-03-23 at 10 29 08 pm

## Types of changes

- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by a-kkwan** [comment]
@peggyopal if you're referring to the mobile day cards having text off of the cards, that is just a temporary solution because later I will need to import Jordan's Day Card component that he made into this file. The temporary cards are just there as mock placeholders!

**Comment by peggyopal** [comment]
@a-kkwan I get that, I just feel like this is merging in a bug that should be fixed before it's merged... But if I'm the only one that feels that way then shoo, all good.

**Comment by a-kkwan** [comment]
Would you say it is better that I leave out the temporary placeholder Day cards from my branch and have it empty for now (no placeholders) instead, then when both this is in master and Jordan's component is in master, integrate accordingly? @peggyopal

**Comment by ert485** [comment]
Jenkins is still failing? Any clue why?

**Comment by a-kkwan** [comment]
@ert485 I believe Jenkins is failing because of a single unit test of uploadSingleFile/not utilizing Firebase, which is a test that is independent of my file. Jenkins was OK with my PR before but that was because I noticed I had the ".only" syntax in my testing which only ran my test case. I removed the ".only", so it ran all test cases of all files and the error is coming from another test file that I did not write.

**Comment by peggyopal** [comment]
@a-kkwan I like the idea of removing the stubs. We shouldn't need them in the repo anyways. :)

**Pull request merged**
