### PR TITLE
Calendar version 2.0 (in some degree)

### PR DESCRIPTION
**Pull request by Yuecheng-Rong**
This PR will change the library of the calendar

## Description

Based on the stakeholder's requirements, we need to change the calendar from Wanderxx to CroudSupport. Link: https://github.com/CroudSupport/vue-fullcalendar
This PR changes the calendar library and has some basic features. Please notice that the main use for the calendar is to print off and read on paper, so some other advanced features might be added later (depends on stakeholder's requirement and time)

Screenshots of the new calendar:
screen shot 2018-03-14 at 6 51 11 pm
screen shot 2018-03-14 at 6 51 17 pm

## Basic feature available for now: 
 -- Show the title and time of the events in the slide store.
The calendar will generate information from slide store directly, filter those slides who's lack of information (title & date) and show events with correct information. If the event has a time, the calendar will show the time of the event as well; If the event does not have a time, it will be considered as an all day event.

## Features might be added later on:
-- Drag the event to change the time/date of the event
The user can drag the event to some other time zone to update the time/date of the event.
screen shot 2018-03-14 at 7 33 06 pm
However, since it need to communicate with the database, it is not a good idea to add this feature now since there's no way to test it. The user can change the information in the Designer view also, so it does not have a very high proirity.

-- Click the event and show the description
screen shot 2018-03-14 at 7 40 27 pm
Since the main use for the calendar is to print off, it won't be useful for now. Maybe we can add that if the stakeholder need that feature.

## Bugs
 -- (not) Interesting (at all) bug No.1
Sometimes the calender does not show correct time, especially between 0AM to 9AM.
screen shot 2018-03-14 at 7 49 32 pm
screen shot 2018-03-14 at 7 53 47 pm
The reason here is the time does not have the correct format. It needs to be "09:45:00" instead of "9:45:00".
Fix: Create a new Date that transfer "yyyy-mm-dd hh:mm:ss" into date string. It works perfect taking date as parameter.
wrong stuff correct
P.S. Another way to fix this problem mentioned by Mahmoud is to use "padStart()". It will automatically add assigned words at the front of the string until the string reaches certain length.
For example:
screen shot 2018-03-15 at 5 23 02 pm
However, there is still potential risk of doing so: what if the time is in format "9:0:0" (Although won't happen except bug appears)?  The padStart will  be hard to fix that, though it can be fixed by new Date. Thus, we will still use "new Date()" here.

 -- (not) Interesting (at all) bug No.2
Sometimes the calendar does not show properly, especially first time load the page
bug
Fix: refresh the page and will be good to go

## How Has This Been Tested?

- [ ] Unit test
- [ ] NightWatch test
- [ ] Coverage testing
- [x] Manual testing

## Test Cases and test paths

There are several manual tests for this component. Please notice that all the data used in test is deleted after test is done.

Result:
screen shot 2018-03-14 at 6 51 11 pm

slides in slide store:

Normal events:
normal events

Events with same date and time:
multi same time event and extend
As you can see, if there are several events that have same date and time, the row will be extended.

Events with no title / no description
no title no description
The one with no title did not show on the calendar. The description, on the other hand, does not matter.

Events with no date / no time
no date no time
The one with no date did not show on the calendar. However, if the event has both title and date but no time, this event will be considered as a all day event. See the right top of the screenshot:
screen shot 2018-03-14 at 6 51 17 pm

Events with wrong date / wrong time
wrong date wrong time
Neither of them will show up in calendar.

## What is new
Update at March 15th: Use "computed()" instead of "created()".
About the "jQuery" implement: jQuery is actually automatically selected by calendar so there is no point to change the jQuery
screen shot 2018-03-15 at 8 44 03 pm

## Types of changes

- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by ert485** [comment]
Did the things Mahmoud mentioned at the standup get changed?
- "pad" the time values
- jquery dependency
- (was there anything else?)

**Comment by ehm011** [comment]
Unit test are in #99

**Comment by Yuecheng-Rong** [comment]
The test needs to run on a mock slide store, so no tests for this part.

**Comment by Yuecheng-Rong** [comment]
Due to the problem found on phone, PR will open after the bug is fixed

**Pull request closed without merging**
